name: Sync Files and Latest.json

on:
  push:
    branches: [ main ]
    paths:
      - 'files/**'
      - 'latest.json'

jobs:
  sync-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Repo
        uses: actions/checkout@v4

      - name: Clone Target Repo
        env:
          TARGET_TOKEN: ${{ secrets.TARGET_REPO_TOKEN }}
        run: |
          git clone "https://x-access-token:$TARGET_TOKEN@github.com/racpast/SNIBypassGUIWebsite.git" target-repo

      - name: Clear Target Directory
        run: rm -rf target-repo/files/*

      - name: Copy Files Recursively
        run: |
          cp -R files/. target-repo/files/
          cp latest.json target-repo/latest.json

      - name: Replace GitHub URLs in latest.json
        run: |
          cd target-repo
          sed -i 's|https://raw.githubusercontent.com/racpast/SNIBypassGUIUpdate/main/files/|https://snibypassgui.netlib.re/files/|g' latest.json

      - name: Commit & Push Changes
        run: |
          cd target-repo
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add -A
          git commit -m "Auto-sync files and update latest.json"
          git push origin main
